kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: radius-gitops
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 8081
        protocol: TCP
      - containerPort: 443
        hostPort: 4444
        protocol: TCP
  - role: worker
  - role: worker
